name: "Build Docker Image And Call Remote"
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gabizou/golang-ci-actions
jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
         docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.15 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f Dockerfile
         image_sha=${docker inspect --format='{{index .Id}}' ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}}
          echo $image_sha
         echo "image_sha=$image_sha" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: docker push ghcr.io/gabizou/golang-ci-actions:latest
      - name: "Notify ActionsReceiverDummy"
        run: |
          curl -X POST https://api.github.com/repos/gabizou/actionsreceiverdummy/dispatches \
                            -H 'Accept: application/vnd.github.everest-preview+json' \
                            -u ${{ secrets.REPO_TOKEN }} \
                           --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "image_sha": "'"${{ env.image_sha }}"'" } }'

