name: "Build Docker Image And Call Remote"
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-20.04
    # These permissions are only necessary to read/publish to
    # GitHub Container Registry, in other cases, it's dependent
    # on the login permissions.
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Clone source repo"
        uses: actions/checkout@v3
        with:
          path: 'source'
      - name: "Generate random file"
        run: echo foo-bar-$(date +%s) > source/generated.txt
      - name: "Clone target repo"
        uses: actions/checkout@v3
        with:
          path: 'target'
          repository: gabizou/ActionsDummy-gen
          token: ${{ secrets.REPO_TOKEN }}
      - name: "Push file as new commit"
        run: |
          echo "TARGET_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo ${{ env.TARGET_TAG }}
          env
          rm -rf target/generated.txt
          cp source/generated.txt target
          cd target
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add generated.txt
          git commit -m "Update generated files for ${{ env.TARGET_TAG }}"