name: "Build Docker Image And Call Remote"
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gabizou/golang-ci-actions
jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-20.04
    # These permissions are only necessary to read/publish to
    # GitHub Container Registry, in other cases, it's dependent
    # on the login permissions.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push Docker image"
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.15 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f Dockerfile
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.15
      - name: "Get image digest"
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }})
          image_sha=$(echo "$digest" | sed -e "s/^ghcr\.io\/gabizou\/golang-ci-actions\@//")
          echo $image_sha
          echo "image_sha=$image_sha" >> $GITHUB_ENV
      - name: "Notify ActionsReceiverDummy"
        run: |
          curl -X POST https://api.github.com/repos/gabizou/actionsreceiverdummy/dispatches \
                            -H 'Accept: application/vnd.github.everest-preview+json' \
                            -u ${{ secrets.REPO_TOKEN }} \
                           --data '{"event_type": "image_uploaded", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "image_sha": "${{ env.image_sha }}" } }'

