name: "Generate and publish command docs"
on:
  push:
jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    env:
      GH_REPO: gabizou/ActionsDummy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          cache: true
      - name: Run generate docs
        run: go run actions-dummy.go
      - name: Upload Release Notes to Wiki
        run: ./.github/build/publish-docs.sh
        env:
          GH_PAT: ${{ secrets.REPO_TOKEN }}
          MD_FOLDER: docs
